---
title: "Alternatives to RUVIII"
output: github_document
---



```{r setup, message = FALSE, warning = FALSE, results='hide'}

knitr::opts_chunk$set(message = FALSE, warning = FALSE, results='hide')

library(Seurat)
library(tidyverse)
library(edgeR)
library(scater)
library(ruv)
library(cluster) #silhouettes
library(factoextra) #silhouettes
library(mvrsquared)

source("/mnt/auxf.R")
path <- ('/domino/datasets/local/RUV')

```


## Preprocessing

### Pseudobulk matrices

```{r pbc}

PBC <- readRDS("/domino/datasets/local/RUV/pblupusds2.rds")
pbps10rep_ds2 <- readRDS("/domino/datasets/local/RUV/pbps10rep_ds2.rds") 

```

### Negative control genes and high variable genes

```{r NCG}

hkGagnon <- read.csv(paste0(path,"/Genes_Gagnon.txt"), sep="")
hkGagnon <- unlist(hkGagnon)
filter.vst <- FindVariableFeatures(PBC,selection.method = 'vst')
high_varg <- which(filter.vst[hkGagnon,]$vst.variance.standardized>1.8)

gene.D <- data.frame(gene=rownames(PBC))
rownames(gene.D) <- gene.D$gene
hk.ind <- rownames(PBC) %in% hkGagnon[-high_varg]

```

### Assigning mock treatment

```{r mock treatment}

subs <- unique(PBC$samples$ind_cov)
set.seed(1)
treatment <- sample(c("A","B"),length(subs), replace=T)

PBC$samples <- PBC$samples %>% left_join(bind_cols(ind_cov = subs, fk.tr = treatment), by='ind_cov')
celltypes <- c('B', 'NK', 'T4', 'T8', 'cDC', 'cM', 'ncM', 'pDC')

```


### data

```{r metrics, echo=FALSE}

split.ct <- function(PBC,ct){
  
  y.ct <- PBC[rowSums(PBC$counts >= 10) >= 5,PBC$samples$cg_cov==ct, keep.lib.sizes=FALSE]
  pmin <- find_p(y.ct)
  y.ct <- calcNormFactors(y.ct, method="upperquartile", p=pmin)
  
  return(y.ct)
}

highvarg <- function(y){
  
  filter.vst <- FindVariableFeatures(y,selection.method = 'vst')
  top_high_varg <- rownames(arrange(filter.vst,-vst.variance.standardized))[1:500]
  
  return(top_high_varg)
}

PCAplot <- function (pca,y,avg_sw2=F,avg_swp=F){
  
  if(isTRUE(avg_sw2|avg_swp)){
   labelgg <- paste0(c('2 PCs: ','10 PCs: '), c(avg_sw2,avg_swp)) 
  }else{
   labelgg <- ""
  }
  
  if(is.null(rownames(pca))){
    rownames(pca)<- y$samples$sample_cell
  }
  
  pos_x <- min(pca[,1])
  pos_y <- min(pca[,2]) 
  ppca <- data.frame(pca) %>%
  tibble::rownames_to_column("sample_cell") %>% # Add the metadata into this data frame; match by sample IDs
  dplyr::inner_join(y$samples, by = "sample_cell") %>% mutate(control= ind_cov=='ICC_control') %>%
  ggplot(aes(x = PC1,y = PC2,color= Processing_Cohort)) + geom_point(aes(shape=pop_cov),size=3) + 
    geom_text(aes(label = ifelse(control, 'control', "")),color='black',vjust = 0, nudge_y = 0.5) + ggtitle("Logcpm plot") +
    labs(color = "Processing cohort", shape = "Ethnicity") + 
    theme_minimal()+ theme(legend.position = "bottom") + scale_color_brewer(palette='Set1')+
    annotate("text", x = c(pos_x+3,pos_x+3), y = c(pos_y+3, pos_y), label = labelgg, size=3, fontface="bold")
    
  return(ppca)
  
}

Silplot <- function (sil){
  
  fviz_silhouette(sil)+ scale_fill_brewer(palette = 'Set1') + 
    scale_color_brewer(palette = 'Set1') + theme_minimal() +
    theme(axis.text.x=element_blank(),legend.position = "bottom") +
    labs(fill="Processing Cohort",color="Processing Cohort")
}

RLEplot <-function(names, logy, samples){
   
  median <- apply(logy, 1, median)
  samples <- as.data.frame(samples)
  
  rle <- apply(logy, 2, function(x) x - median)
  dataplot <- as.data.frame(rle) %>% 
    pivot_longer(everything(),names_to = 'sample_cell') %>% 
    left_join(samples, by='sample_cell')
  
  dataplot$sample_cell <- fct_relevel(dataplot$sample_cell,names)
  
  ggplot(dataplot,aes(x=sample_cell, y=value,colour = Processing_Cohort, linetype=pop_cov )) +
    geom_boxplot(outlier.shape = NA) + ylim(-2,2) + scale_color_brewer(palette='Set1') + ggtitle("RLE plot") +
     geom_hline(yintercept=0, linetype='dashed') + labs(y="Relative log expression", color='Processing cohort')+
    theme_minimal()+ theme( legend.position = 'bottom',strip.text =element_blank(),
                            axis.title.x = element_blank(),
                            axis.text.x = element_blank(),
                            axis.ticks.x = element_blank())

}

histpvals <- function(y){
  
  design <- model.matrix(~ y$samples$fk.tr ) 
  colnames(design) <- c('Intercept','Managed')
  v <- voom(y, design, plot=F) 
  vfit <- lmFit(v, design)
  efit <- eBayes(vfit)
  pvalsUQ <- topTable(efit, coef=2, number=dim(y)[1], adjust="BH")
  
  ggplot(pvalsUQ, aes(x=P.Value)) + geom_histogram(bins=15) + scale_color_brewer(palette='Set1') + ggtitle("P-values histogram") + theme_minimal()
  
}
```

```{r raw data, results='hide'}

ys.ct <- lapply(celltypes,split.ct,PBC=PBC) # split dataset, compute norm factors for UQ normalisation
hvgs <- lapply(ys.ct, highvarg) # high variable genes for PCA
logys.ct <- lapply(ys.ct,function(y) voom(y)$E) #cpm transformation

```




### RUVIII

```{r ruviii, results='hide', echo=FALSE}


histT <- function (y,w,samples){
  k <- ncol(w)
  design <- model.matrix(~ samples$fk.tr + w + samples$pop_cov) 
  colnames(design) <- c('Intercept','fk.tr', paste0("W",1:k), 'pop')
  v <- voom(y, design, plot=F) 
  vfit <- lmFit(v, design)
  efit <- eBayes(vfit)
  pvalsT <- topTable(efit, coef=2, number=dim(y)[1], adjust="BH")
  
  ggplot(pvalsT, aes(x=P.Value)) + geom_histogram(bins=15) + scale_color_brewer(palette='Set1') + ggtitle("P-values histogram") + theme_minimal()
}



Mcts.ct <- lapply (ys.ct, function(x){
  Mct <- replicate.matrix(x$samples$ind_cov)
  rownames(Mct) <- x$samples$ind_cov
  Mct
})

k=5

ruv3T2 <- mapply(RUVIIIW, Y = lapply(logys.ct,t), M=Mcts.ct , ctl =  lapply(ys.ct, function (x) rownames(x) %in% hkGagnon[-high_varg]), k= as.list(rep(k,length(celltypes))), return.info=as.list(rep(T,length(celltypes))), SIMPLIFY=F)


normT2 <- lapply(ruv3T2,function (x) t(x$newY))
hvgs <- lapply(normT2, highvarg)
pcas <- mapply(calculatePCA,x=normT2, subset_row=hvgs, ncomponents=10, SIMPLIFY = F)
pcos <- lapply(ys.ct, function (x) as.integer(x$samples$Processing_Cohort))

sil2s <- mapply(silhouette,x=pcos,dist=lapply(pcas,function(x) dist(x[,1:2],"euclidean") ), SIMPLIFY = F)
silps <- mapply(silhouette,x=pcos,dist=lapply(pcas,dist, "manhattan") ,SIMPLIFY = F)

avgs_sw2 <- lapply(sil2s, function (x) round(mean(x[,3]),2))
avgs_swp <- lapply(silps, function (x) round(mean(x[,3]),2))

ordnames <- lapply(ys.ct, function (x) arrange(x$samples,Processing_Cohort)$'sample_cell') 

SilplotsT23 <- lapply(silps,Silplot)

PCAplotsT23 <- mapply(PCAplot, pca= pcas, y=ys.ct, SIMPLIFY = F)

RLEplotsT23 <- mapply(RLEplot, names= ordnames, logy=normT2,samples= map(ys.ct,'samples'), SIMPLIFY = F)


HistsT23 <- mapply(histT,y=ys.ct,w=map(ruv3T2,"W"),map(ys.ct,'samples'),SIMPLIFY = F)

### fix
apply(ruv3T2$W,2, function (x) kruskal.test(x ~ pbc.metaD$Processing_Cohort[pbc.metaD$cg_cov==ct]))



```

### RUVIII + Batch

```{r ruviii batch, results='hide', echo=FALSE}


normruvbatch <- function(y,w){
  
  design <- model.matrix(~ y$samples$fk.tr + w +
                           y$samples$Processing_Cohort + y$samples$pop_cov ) 
  colnames(design) <- c('(Intercept)','tr', paste0("W",1:k), 
                        paste0('Proc', 2:4), 'pop')
  v <- voom(y, design, plot=F) 
  vfit <- lmFit(v, design)
  alpha <- vfit$coefficients[,c(paste0("W",1:k),paste0('Proc', 2:4))] # same coefficients as efit and returned by toptable
  
  newY <- v$E - t(design[,c(paste0("W",1:k),paste0('Proc', 2:4))] %*% t(alpha))
  
  return(newY)
}


WS <- lapply(ruv3T2, function(x) x$W)

normT2 <- mapply(normruvbatch, y = ys.ct, w= WS, SIMPLIFY = F)
hvgs <- lapply(normT2, highvarg)
pcas <- mapply(calculatePCA,x=normT2, subset_row=hvgs, ncomponents=10, SIMPLIFY = F)
pcos <- lapply(ys.ct, function (x) as.integer(x$samples$Processing_Cohort))

sil2s <- mapply(silhouette,x=pcos,dist=lapply(pcas,function(x) dist(x[,1:2],"euclidean") ), SIMPLIFY = F)
silps <- mapply(silhouette,x=pcos,dist=lapply(pcas,dist, "manhattan") ,SIMPLIFY = F)

avgs_sw2 <- lapply(sil2s, function (x) round(mean(x[,3]),2))
avgs_swp <- lapply(silps, function (x) round(mean(x[,3]),2))

ordnames <- lapply(ys.ct, function (x) arrange(x$samples,Processing_Cohort)$'sample_cell') 

SilplotsT2 <- lapply(silps,Silplot)

PCAplotsT2 <- mapply(PCAplot, pca= pcas, y=ys.ct, SIMPLIFY = F)

RLEplotsT2 <- mapply(RLEplot, names= ordnames, logy=normT2,samples= map(ys.ct,'samples'), SIMPLIFY = F)


HistsT2 <- mapply(histT,y=ys.ct,w=map(ruv3T2,"W"),map(ys.ct,'samples'),SIMPLIFY = F)



mc <- function (y,w){
  
  fit <- lm( w~y$samples$Processing_Cohort)
  yhat <- predict(fit, y$samples$Processing_Cohort, type = "raw")
  r2_mv2 <- calc_rsquared(y = w, yhat = yhat)
  
  return(r2_mv2)
}

mcT2 <- mapply(mc, y = ys.ct, w= WS, SIMPLIFY = F)


```


### RUVIII PBPS


```{r ruviii PBPS, results='hide', echo=FALSE}

fullcount <- pbps10rep_ds2[[1]]
sifull <- pbps10rep_ds2[[2]]

ps.pbc <- fullcount[,sifull$cg_cov==ct]
ps.pbc <- ps.pbc[rowSums(bc >= 10) >= 5,]
ps.pbc <-  ps.pbc[rownames(pbc),]
ps.y <- DGEList(counts=ps.pbc )
pmin <- find_p(ps.pbc )
ps.y <- calcNormFactors(ps.y, method="upperquartile", p=pmin)
ps.nf <- ps.y$samples$norm.factors
ps.logy <- voom(ps.y,plot=F)$E

ps.M <- replicate.matrix(sifull$ind_cov[sifull$cg_cov==ct])
rownames(ps.M) <- sifull$ind_cov[sifull$cg_cov==ct]

ruv3ps <- RUVIIIW(Y = t(ps.logy), M = ps.M, ctl = hk.ind,  k = k,
                  return.info = T)

orig.s <- sifull$sample_cell[sifull$cg_cov==ct & sifull$pbps==0]


```

